/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.awt.Color;

/**
 *
 * @author Samruddhi
 */
public class searchpage extends javax.swing.JFrame {

    /**
     * Creates new form searchpage
     */
    public searchpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbar = new javax.swing.JPanel();
        search_box = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        titles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        result4 = new javax.swing.JPanel();
        result5 = new javax.swing.JPanel();
        img5 = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        cate5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        result6 = new javax.swing.JPanel();
        img6 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        cate6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        result7 = new javax.swing.JPanel();
        img7 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        cate7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        result8 = new javax.swing.JPanel();
        img8 = new javax.swing.JLabel();
        title8 = new javax.swing.JLabel();
        cate8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        result9 = new javax.swing.JPanel();
        img9 = new javax.swing.JLabel();
        title9 = new javax.swing.JLabel();
        cate9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        searchbar.setBackground(new java.awt.Color(11, 11, 11));

        search_box.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        search_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_boxActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Search_18px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchbarLayout = new javax.swing.GroupLayout(searchbar);
        searchbar.setLayout(searchbarLayout);
        searchbarLayout.setHorizontalGroup(
            searchbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchbarLayout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchbarLayout.setVerticalGroup(
            searchbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchbarLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(searchbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_box))
                .addContainerGap())
        );

        titles.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 48)); // NOI18N
        titles.setText("Titles");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 500));

        result4.setBackground(new java.awt.Color(255, 255, 255));

        result5.setBackground(new java.awt.Color(255, 255, 255));
        result5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));

        img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N

        title5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        title5.setText("Movie Title");
        title5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        title5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                title5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                title5MouseExited(evt);
            }
        });

        cate5.setText("Category");

        jLabel1.setText("Rating : 9.1");

        javax.swing.GroupLayout result5Layout = new javax.swing.GroupLayout(result5);
        result5.setLayout(result5Layout);
        result5Layout.setHorizontalGroup(
            result5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(img5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(result5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cate5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        result5Layout.setVerticalGroup(
            result5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, result5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(result5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(result5Layout.createSequentialGroup()
                        .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cate5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(img5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        result6.setBackground(new java.awt.Color(255, 255, 255));
        result6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N

        title6.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        title6.setText("Movie Title");
        title6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        title6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                title6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                title6MouseExited(evt);
            }
        });

        cate6.setText("Category");

        jLabel2.setText("Rating : 9.1");

        javax.swing.GroupLayout result6Layout = new javax.swing.GroupLayout(result6);
        result6.setLayout(result6Layout);
        result6Layout.setHorizontalGroup(
            result6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(img6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(result6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cate6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(595, Short.MAX_VALUE))
        );
        result6Layout.setVerticalGroup(
            result6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(result6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(result6Layout.createSequentialGroup()
                        .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cate6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(img6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        result7.setBackground(new java.awt.Color(255, 255, 255));
        result7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        img7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N

        title7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        title7.setText("Movie Title");
        title7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        title7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                title7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                title7MouseExited(evt);
            }
        });

        cate7.setText("Category");

        jLabel4.setText("Rating : 9.1");

        javax.swing.GroupLayout result7Layout = new javax.swing.GroupLayout(result7);
        result7.setLayout(result7Layout);
        result7Layout.setHorizontalGroup(
            result7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(img7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(result7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cate7)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        result7Layout.setVerticalGroup(
            result7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(result7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(result7Layout.createSequentialGroup()
                        .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cate7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(img7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        result8.setBackground(new java.awt.Color(255, 255, 255));
        result8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        img8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N

        title8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        title8.setText("Movie Title");
        title8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        title8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                title8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                title8MouseExited(evt);
            }
        });

        cate8.setText("Category");

        jLabel3.setText("Rating : 9.1");

        javax.swing.GroupLayout result8Layout = new javax.swing.GroupLayout(result8);
        result8.setLayout(result8Layout);
        result8Layout.setHorizontalGroup(
            result8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(img8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(result8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cate8)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        result8Layout.setVerticalGroup(
            result8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result8Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(img8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(result8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(title8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cate8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        result9.setBackground(new java.awt.Color(255, 255, 255));
        result9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        img9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.jpg"))); // NOI18N

        title9.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        title9.setText("Movie Title");
        title9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        title9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                title9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                title9MouseExited(evt);
            }
        });

        cate9.setText("Category");

        jLabel6.setText("Rating : 9.1");

        javax.swing.GroupLayout result9Layout = new javax.swing.GroupLayout(result9);
        result9.setLayout(result9Layout);
        result9Layout.setHorizontalGroup(
            result9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(img9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(result9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cate9)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        result9Layout.setVerticalGroup(
            result9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result9Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(result9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(result9Layout.createSequentialGroup()
                        .addComponent(title9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cate9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(img9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout result4Layout = new javax.swing.GroupLayout(result4);
        result4.setLayout(result4Layout);
        result4Layout.setHorizontalGroup(
            result4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(result4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(result4Layout.createSequentialGroup()
                        .addGroup(result4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(result5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(result6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(result8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(result7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(result9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        result4Layout.setVerticalGroup(
            result4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(result4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titles, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titles, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_boxActionPerformed

    private void title6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title6MouseEntered
    title6.setForeground(new Color(153,153,153));        // TODO add your handling code here:
    }//GEN-LAST:event_title6MouseEntered

    private void title6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title6MouseExited
      title6.setForeground(new Color(0,0,0));    // TODO add your handling code here:
    }//GEN-LAST:event_title6MouseExited

    private void title5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title5MouseEntered
   title5.setForeground(new Color(153,153,153));         // TODO add your handling code here:
    }//GEN-LAST:event_title5MouseEntered

    private void title5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title5MouseExited
   title5.setForeground(new Color(0,0,0));          // TODO add your handling code here:
    }//GEN-LAST:event_title5MouseExited

    private void title8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title8MouseEntered
title8.setForeground(new Color(153,153,153));          // TODO add your handling code here:
    }//GEN-LAST:event_title8MouseEntered

    private void title8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title8MouseExited
title8.setForeground(new Color(0,0,0));          // TODO add your handling code here:
    }//GEN-LAST:event_title8MouseExited

    private void title7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title7MouseEntered
title7.setForeground(new Color(153,153,153));          // TODO add your handling code here:
    }//GEN-LAST:event_title7MouseEntered

    private void title7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title7MouseExited
title7.setForeground(new Color(0,0,0));          // TODO add your handling code here:
    }//GEN-LAST:event_title7MouseExited

    private void title9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title9MouseEntered
title9.setForeground(new Color(153,153,153));          // TODO add your handling code here:
    }//GEN-LAST:event_title9MouseEntered

    private void title9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_title9MouseExited
title9.setForeground(new Color(0,0,0));          // TODO add your handling code here:
    }//GEN-LAST:event_title9MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cate5;
    private javax.swing.JLabel cate6;
    private javax.swing.JLabel cate7;
    private javax.swing.JLabel cate8;
    private javax.swing.JLabel cate9;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JLabel img8;
    private javax.swing.JLabel img9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel result4;
    private javax.swing.JPanel result5;
    private javax.swing.JPanel result6;
    private javax.swing.JPanel result7;
    private javax.swing.JPanel result8;
    private javax.swing.JPanel result9;
    private javax.swing.JTextField search_box;
    private javax.swing.JPanel searchbar;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JLabel titles;
    // End of variables declaration//GEN-END:variables
}
